name: Device Support request
description: Create a issue to support a device which is not currently supported in the zigbee adapter. Unsupported devices are reported as `supported:false` during pairing.
labels: [devicesupport]
body:
    - type: markdown
      attributes:
          value: |
              **IMPORTANT:**
              - **Handling device support issues is impossible without physical access to a device of this exact type. It is safe to assume that none of the developers have said device, and it is wrong to assume that developes will spend their money to purchase a device for integration!**
              - Resolving the issue requires **your participation**, which may include physical access to **your device** by one of the developers. Do not open an issue unless you are willing to actively participate in its resolution.
              - check whether your [device](https://www.zigbee2mqtt.io/supported-devices/) is listed as supported at zigbee2mqtt.io. Any device without a link to zigbee2mqtt.io will be assumed not supported - integration of these devices requires physical access to the device, so it is unlikely that any work will be done on it in this project.
              - ensure that both the manufacturer and the model match between your device and the listed device.
              - identify required ZHC version! This is **not** the currently installed ZHC version. The description of the entry field contains an explanation how to identify this version. Issues opened without a proper entry in this field are considered **incomplete**.
              - **do NOT open an issue without at least testing with the current latest or github version.** Issues where device integration has not been tested in this manner are considererd **incomplete**.
              - **Incomplete issues - i.e. issues with one of the required fields not filled in properly or where device-integration has been tested with the current stable version only - will be automatically closed after 7 days.**
    - type: input
      id: zigbee_version
      attributes:
          label: Tested with adapter version (Test with latest and/or GitHub Version required)
          placeholder: '1.10.15'
      validations:
          required: true    
    - type: input
      id: model_zigbee
      attributes:
          label: modelZigbee
          description: Can be found on the info-panel accessible from the backside of the device tile in the Admin GUI / Zigbee Tab
          placeholder: 'TS0601'
      validations:
          required: true         
    - type: input
      id: manufacturer
      attributes:
          label: manufacturer
          description: Can be found on the info-panel accessible from the backside of the device tile in the Admin GUI / Zigbee Tab
          placeholder: '_TZ3000_upgcbody'
      validations:
          required: true          
    - type: input
      id: ZHC_Version
      attributes:
          label: min. ZHC version
          description: Search the changelog at https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/CHANGELOG.md for the Model Name, the reported modelZigbee or manufacturer entry. If this provides no clear result, enter 'unsupported' into this field.
          placeholder: '23.0.0'
      validations:
          required: true
    - type: input
      id: Link_to_device
      attributes:
          label: Link to device
          description: Post the link of the device listing on zigbee2mqtt.io
          placeholder: 'https://www.zigbee2mqtt.io/supported-devices/'
      validations:
          required: false          
    - type: input
      id: coordinator_type_a
      attributes:
          label: Coordinator type selected in adapter setting
          description: The selection made for the coordinator-type in the adapters settings.
          placeholder: 'TI Z-Stack/CCxxxx'
      validations:
          required: false
    - type: input
      id: coordinator_type
      attributes:
          label: Coordinator 
          description: Hardware Coordinator
          placeholder: Electrolama zig-a-zig-ah! (zzh!), Slaeshs CC2652RB stick, SONOFF Zigbee 3.0 USB Dongle Plus ...
      validations:
          required: false                    
    - type: input
      id: coordinator_fwversion
      attributes:
          label: Coordinator firmware version and revision
          description: Both firmware version and revision are shown on the Device tile for the coordinator in the Admin GUI / Zigbee Tab
          placeholder: 'version 2-1.2.7.1., revision 20191106'
      validations:
          required: false
         
