const states = {
    click: {
        id: 'click',
        name: 'Click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    double_click: {
        id: 'double_click',
        prop: 'double',
        name: 'Double click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    triple_click: {
        id: 'double_click',
        prop: 'triple',
        name: 'Triple click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    quad_click: {
        id: 'quad_click',
        prop: 'quadruple',
        name: 'Quadruple click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    long_click: {
        id: 'long_click',
        prop: 'long',
        name: 'Long click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    voltage: {
        id: 'voltage',
        name: 'Battery voltage',
        icon: '/icons/battery_v.png',
        role: 'battery.voltage',
        write: false,
        read: true,
        type: 'number',
        unit: 'V'
    },
    battery: {
        id: 'battery',
        name: 'Battery percent',
        icon: '/icons/battery_p.png',
        role: 'battery.percent',
        write: false,
        read: true,
        type: 'number',
        unit: '%',
        min: 0,
        max: 100
    },
    left_click: {
        id: 'left_click',
        prop: 'left',
        name: 'Left click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    right_click: {
        id: 'right_click',
        prop: 'right',
        name: 'Right click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    both_click: {
        id: 'both_click',
        prop: 'both',
        name: 'Both click event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    state: {
        id: 'state',
        name: 'Switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean'
    },
    left_state: {
        id: 'left_state',
        prop: 'l1',
        name: 'Left switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean'
    },
    right_state: {
        id: 'right_state',
        prop: 'l2',
        name: 'Right switch state',
        icon: undefined,
        role: 'switch',
        write: true,
        read: true,
        type: 'boolean'
    },
    temperature: {
        id: 'temperature',
        name: 'Temperature',
        icon: undefined,
        role: 'value.temperature',
        write: false,
        read: true,
        type: 'number',
        unit: '°C'
    },
    humidity: {
        id: 'humidity',
        name: 'Humidity',
        icon: undefined,
        role: 'value.humidity',
        write: false,
        read: true,
        type: 'number',
        unit: '%',
        min: 0,
        max: 100
    },
    pressure: {
        id: 'pressure',
        name: 'Pressure',
        icon: undefined,
        role: 'value.pressure',
        write: false,
        read: true,
        type: 'number',
        unit: 'Pa',
        min: 0,
        max: 100
    },
    illuminance: {
        id: 'illuminance',
        name: 'Illuminance',
        icon: undefined,
        role: 'value.lux',
        write: false,
        read: true,
        type: 'number',
        unit: 'lux'
    },
    occupancy: {
        id: 'occupancy',
        name: 'Occupancy',
        icon: undefined,
        role: 'indicator.motion',
        write: false,
        read: true,
        type: 'boolean'
    },
    no_motion: {
        id: 'no_motion',
        name: 'Last motion',
        icon: undefined,
        role: 'state',
        write: false,
        read: true,
        type: 'number',
        unit: 'seconds'
    },
    contact: {
        id: 'contact',
        name: 'Contact event',
        icon: undefined,
        role: 'state',
        write: false,
        read: true,
        type: 'boolean'
    },
    water_detected: {
        id: 'detected',
        prop: 'water_leak',
        name: 'Water leak detected',
        icon: undefined,
        role: 'indicator.leakage',
        write: false,
        read: true,
        type: 'boolean'
    },
    gas_detected: {
        id: 'detected',
        prop: 'smoke',
        name: 'Gas leak detected',
        icon: undefined,
        role: 'indicator.alarm.fire',
        write: false,
        read: true,
        type: 'boolean'
    },
    shake: {
        id: 'shake',
        name: 'Shake event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    wakeup: {
        id: 'wakeup',
        name: 'Wakeup event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    fall: {
        id: 'fall',
        name: 'Free fall event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    tap: {
        id: 'tap',
        name: 'Tapped twice event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    slide: {
        id: 'slide',
        name: 'Slide event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    flip180: {
        id: 'flip180',
        name: 'Flip on 180°',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    flip90: {
        id: 'flip90',
        name: 'Flip on 90° event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    rotate_left: {
        id: 'rotate_left',
        name: 'Rotate left event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    rotate_right: {
        id: 'rotate_right',
        name: 'Rotate right event',
        icon: undefined,
        role: 'button',
        write: false,
        read: true,
        type: 'boolean',
        isEvent: true,
    },
    load_power: {
        id: 'load_power',
        prop: 'power',
        name: 'Load power',
        icon: undefined,
        role: 'value.power',
        write: false,
        read: true,
        type: 'number',
        unit: 'W'
    },
    brightness: {
        id: 'brightness',
        name: 'Brightness',
        icon: undefined,
        role: 'level.dimmer',
        write: true,
        read: true,
        type: 'number',
        unit: '%',
        min: 0,
        max: 100
    },
    colortemp: {
        id: 'colortemp',
        prop: 'color_temp',
        name: 'Color temperature',
        icon: undefined,
        role: 'level.temperature',
        write: true,
        read: true,
        type: 'number'
    },
}


const devices = {
    'lumi.sensor_switch': {
        icon: 'img/xiaomi_wireless_switch.png',
        states: [states.click, states.double_click, states.triple_click, states.quad_click, 
            states.long_click, states.voltage, states.battery],
    },
    'lumi.sensor_switch.aq2': {
        icon: 'img/aqara.switch.png',
        states: [states.click, states.double_click, states.voltage, states.battery],
    },
    'lumi.sensor_86sw1\u0000lu': {
        icon: '',
        states: [states.click, states.voltage, states.battery],
    },
    'lumi.sensor_86sw2\u0000Un': {
        icon: 'img/86sw2.png',
        states: [states.left_click, states.right_click, states.both_click, states.voltage, states.battery],
    },
    'lumi.ctrl_neutral1': {
        icon: '',
        states: [states.click, states.state],
    },
    'lumi.ctrl_neutral2': {
        icon: 'img/ctrl_neutral2.png',
        states: [states.left_click, states.right_click, states.both_click, states.left_state, states.right_state],
    },
    'lumi.sens': {
        icon: 'img/sensor_ht.png',
        states: [states.temperature, states.humidity, states.voltage, states.battery],
    },
    'lumi.weather': {
        icon: 'img/aqara_temperature_sensor.png',
        states: [states.temperature, states.humidity, states.pressure, states.voltage, states.battery],
    },
    'lumi.sensor_motion': {
        icon: 'img/aqara_numan_body_sensor.png',
        states: [states.occupancy, states.no_motion, states.voltage, states.battery],
    },
    'lumi.sensor_motion.aq2': {
        icon: 'img/aqara_numan_body_sensor.png',
        states: [states.occupancy, states.no_motion, states.illuminance, states.voltage, states.battery],
    },
    'lumi.sensor_magnet': {
        icon: 'img/magnet.png',
        states: [states.contact, states.voltage, states.battery],
    },
    'lumi.sensor_magnet.aq2': {
        icon: 'img/sensor_magnet_aq2.png',
        states: [states.contact, states.voltage, states.battery],
    },
    'lumi.sensor_wleak.aq1': {
        icon: 'img/sensor_wleak_aq1.png',
        states: [states.water_detected, states.voltage, states.battery],
    },
    'lumi.sensor_cube': {
        icon: 'img/cube.png',
        states: [states.shake, states.wakeup, states.fall, states.tap, states.slide, states.flip180, 
            states.flip90, states.rotate_left, states.rotate_right, states.voltage, states.battery],
    },
    'sensor_cube.aqgl01': {
        icon: 'img/cube.png',
        states: [states.shake, states.wakeup, states.fall, states.tap, states.slide, states.flip180, 
            states.flip90, states.rotate_left, states.rotate_right, states.voltage, states.battery],
    },
    'lumi.plug': {
        icon: 'img/plug.png',
        states: [states.state, states.load_power],
    },
    'lumi.ctrl_86plug': {
        icon: 'img/86plug.png',
        states: [states.state, states.load_power],
    },
    'lumi.sensor_smoke': {
        icon: 'img/smoke.png',
        states: [states.gas_detected, states.voltage, states.battery],
    },

    // IKEA
    'TRADFRI bulb E27 WS opal 980lm': {
        icon: 'img/TRADFRI.bulb.E27.png',
        states: [states.state, states.brightness, states.colortemp],
    },
    // LED1623G12 uses 2 model IDs, see https://github.com/Koenkk/zigbee2mqtt/issues/21
    'TRADFRI bulb E27 opal 1000lm': {
        icon: 'img/TRADFRI.bulb.E27.png',
        states: [states.state, states.brightness, states.colortemp],
    },
    'TRADFRI bulb E27 W opal 1000lm': {
        icon: 'img/TRADFRI.bulb.E27.png',
        states: [states.state, states.brightness, states.colortemp],
    },
    'TRADFRI bulb GU10 WS 400lm': {
        icon: 'img/TRADFRI.bulb.E27.png',
        states: [states.state, states.brightness, states.colortemp],
    },
    'TRADFRI bulb GU10 W 400lm': {
        icon: undefined,
        states: [states.state, states.brightness],
    },
    // LED1536G5 has an E12 and E14 version.
    'TRADFRI bulb E14 WS opal 400lm': {
        icon: undefined,
        states: [states.state, states.brightness, states.colortemp],
    },
    'TRADFRI bulb E12 WS opal 400lm': {
        icon: undefined,
        states: [states.state, states.brightness, states.colortemp],
    },
    'TRADFRI bulb E26 opal 1000lm': {
        icon: undefined,
        states: [states.state, states.brightness],
    },
    'TRADFRI bulb GU10 WS 400lm': {
        icon: 'img/TRADFRI.bulb.E27.png',
        states: [states.state, states.brightness, states.colortemp],
    },
    'FLOALT panel WS': {
        icon: 'img/FLOALT.panel.WS.png',
        states: [states.state, states.brightness, states.colortemp],
    }
}

module.exports = devices;