/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Zigbee adapter": {                              "en": "Zigbee adapter",                                  "de": "Zigbee adapter",                                  "ru": "Zigbee драйвер",                                  "pt": "Zigbee adapter",                                  "nl": "Zigbee adapter",                                  "fr": "Zigbee adapter",                                  "it": "Zigbee adapter",                                  "es": "Zigbee adapter"},
    "COM port name": {                               "en": "COM port name",                                   "de": "COM port name",                                   "ru": "Имя или адрес порта",                             "pt": "COM port name",                                   "nl": "COM port name",                                   "fr": "COM port name",                                   "it": "COM port name",                                   "es": "COM port name"},
    "Let's pairing!": {                              "en": "Let's pairing!",                                  "de": "Let's pairing!",                                  "ru": "Давай спариваться!",                              "pt": "Let's pairing!",                                  "nl": "Let's pairing!",                                  "fr": "Let's pairing!",                                  "it": "Let's pairing!",                                  "es": "Let's pairing!"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Наименование",                                    "pt": "Name",                                            "nl": "Name",                                            "fr": "Name",                                            "it": "Name",                                            "es": "Name"},
    "Save": {                                        "en": "Save",                                            "de": "Save",                                            "ru": "Сохранить",                                       "pt": "Save",                                            "nl": "Save",                                            "fr": "Save",                                            "it": "Save",                                            "es": "Save"},
    "Yes": {                                         "en": "Yes",                                             "de": "Yes",                                             "ru": "Да",                                              "pt": "Yes",                                             "nl": "Yes",                                             "fr": "Yes",                                             "it": "Yes",                                             "es": "Yes"},
    "Cancel": {                                      "en": "Cancel",                                          "de": "Cancel",                                          "ru": "Отменить",                                        "pt": "Cancel",                                          "nl": "Cancel",                                          "fr": "Cancel",                                          "it": "Cancel",                                          "es": "Cancel"},
    "Pairing process": {                             "en": "Pairing process",                                 "de": "Pairing process",                                 "ru": "Процесс спаривания",                              "pt": "Pairing process",                                 "nl": "Pairing process",                                 "fr": "Pairing process",                                 "it": "Pairing process",                                 "es": "Pairing process"},
    "Hide": {                                        "en": "Hide",                                            "de": "Hide",                                            "ru": "Скрыть",                                          "pt": "Hide",                                            "nl": "Hide",                                            "fr": "Hide",                                            "it": "Hide",                                            "es": "Hide"},
    "Do you really whant to delete device": {        "en": "Do you really whant to delete device",            "de": "Do you really whant to delete device",            "ru": "Вы действительно хотите удалить устройство",      "pt": "Do you really whant to delete device",            "nl": "Do you really whant to delete device",            "fr": "Do you really whant to delete device",            "it": "Do you really whant to delete device",            "es": "Do you really whant to delete device"},
    "Rename device": {                               "en": "Rename device",                                   "de": "Rename device",                                   "ru": "Переименовать устройство",                        "pt": "Rename device",                                   "nl": "Rename device",                                   "fr": "Rename device",                                   "it": "Rename device",                                   "es": "Rename device"},
    "Enter new name": {                              "en": "Enter new name",                                  "de": "Enter new name",                                  "ru": "Введите новое имя",                               "pt": "Enter new name",                                  "nl": "Enter new name",                                  "fr": "Enter new name",                                  "it": "Enter new name",                                  "es": "Enter new name"},
    "Delete confirmation": {                         "en": "Delete confirmation",                             "de": "Delete confirmation",                             "ru": "Подтвердите удаление",                            "pt": "Delete confirmation",                             "nl": "Delete confirmation",                             "fr": "Delete confirmation",                             "it": "Delete confirmation",                             "es": "Delete confirmation"},
    "Devices": {                                     "en": "Devices",                                         "de": "Devices",                                         "ru": "Устройства",                                      "pt": "Devices",                                         "nl": "Devices",                                         "fr": "Devices",                                         "it": "Devices",                                         "es": "Devices"},
    "Network map": {                                 "en": "Network map",                                     "de": "Network map",                                     "ru": "Карта сети",                                      "pt": "Network map",                                     "nl": "Network map",                                     "fr": "Network map",                                     "it": "Network map",                                     "es": "Network map"},
    "Settings": {                                    "en": "Settings",                                        "de": "Settings",                                        "ru": "Настройки",                                       "pt": "Settings",                                        "nl": "Settings",                                        "fr": "Settings",                                        "it": "Settings",                                        "es": "Settings"},
    "Channel": {                                     "en": "Channel",                                         "de": "Channel",                                         "ru": "Канал",                                           "pt": "Channel",                                         "nl": "Channel",                                         "fr": "Channel",                                         "it": "Channel",                                         "es": "Channel"},
}; 