/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "COM port name": {                               "en": "COM port name",                                   "de": "COM-Anschlussname",                               "ru": "Имя или адрес порта",                             "pt": "Nome da porta COM",                               "nl": "COM-poortnaam",                                   "fr": "Nom du port COM",                                 "it": "Nome della porta COM",                            "es": "Nombre del puerto COM",                           "pl": "Nazwa portu COM"},
    "Cancel": {                                      "en": "Cancel",                                          "de": "Abbrechen",                                       "ru": "Отменить",                                        "pt": "Cancelar",                                        "nl": "Annuleer",                                        "fr": "Annuler",                                         "it": "Annulla",                                         "es": "Cancelar",                                        "pl": "Anuluj"},
    "Channel": {                                     "en": "Channel",                                         "de": "Kanal",                                           "ru": "Канал",                                           "pt": "Canal",                                           "nl": "Kanaal",                                          "fr": "Canal",                                           "it": "Canale",                                          "es": "Canal",                                           "pl": "Kanał"},
    "Delete confirmation": {                         "en": "Delete confirmation",                             "de": "Löschen Sie die Bestätigung",                     "ru": "Подтвердите удаление",                            "pt": "Excluir confirmação",                             "nl": "Bevestiging verwijderen",                         "fr": "Supprimer la confirmation",                       "it": "Cancella conferma",                               "es": "Eliminar confirmación",                           "pl": "Usuń potwierdzenie"},
    "Devices": {                                     "en": "Devices",                                         "de": "Geräte",                                          "ru": "Устройства",                                      "pt": "Devices",                                         "nl": "apparaten",                                       "fr": "Dispositifs",                                     "it": "dispositivi",                                     "es": "Dispositivos",                                    "pl": "Pomysłowość"},
    "Disable LED for cc2531": {                      "en": "Disable LED for cc2531",                          "de": "LED auf CC2531 deaktivieren",                     "ru": "Выключить индикатор для cc2531",                  "pt": "Desativar LED para cc2531",                       "nl": "Schakel LED uit voor cc2531",                     "fr": "Désactiver le voyant pour cc2531",                "it": "Disabilita LED per cc2531",                       "es": "Desactivar LED para cc2531",                      "pl": "Wyłącz LED dla cc2531"},
    "Do you really whant to delete device": {        "en": "Do you really whant to delete device",            "de": "Möchten Sie das Gerät wirklich löschen?",         "ru": "Вы действительно хотите удалить устройство",      "pt": "Você realmente quer deletar o dispositivo",       "nl": "Wil je echt het apparaat verwijderen?",           "fr": "Voulez-vous vraiment supprimer l'appareil?",      "it": "Vuoi davvero eliminare il dispositivo",           "es": "¿Realmente quieres borrar dispositivo?",          "pl": "Czy naprawdę chcesz usunąć urządzenie?"},
    "Enter new name": {                              "en": "Enter new name",                                  "de": "Geben Sie einen neuen Namen ein",                 "ru": "Введите новое имя",                               "pt": "Digite um novo nome",                             "nl": "Voer een nieuwe naam in",                         "fr": "Entrez un nouveau nom",                           "it": "Inserisci un nuovo nome",                         "es": "Ingresa un nuevo nombre",                         "pl": "Wprowadź nową nazwę"},
    "Hide": {                                        "en": "Hide",                                            "de": "Verbergen",                                       "ru": "Скрыть",                                          "pt": "ocultar",                                         "nl": "Verbergen",                                       "fr": "Cacher",                                          "it": "Nascondere",                                      "es": "Esconder",                                        "pl": "Ukryć"},
    "Let's pairing!": {                              "en": "Let's pairing!",                                  "de": "Geräte paaren!",                                  "ru": "Давай спарим устройства!",                        "pt": "Vamos emparelhar!",                               "nl": "Laten we paren!",                                 "fr": "Apparions!",                                      "it": "Facciamo coppia!",                                "es": "Vamos a emparejar!",                              "pl": "Sparujmy się!"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Наименование",                                    "pt": "Nome",                                            "nl": "Naam",                                            "fr": "prénom",                                          "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię"},
    "Network map": {                                 "en": "Network map",                                     "de": "Netzwerkkarte",                                   "ru": "Карта сети",                                      "pt": "Mapa de rede",                                    "nl": "Netwerkkaart",                                    "fr": "Carte du réseau",                                 "it": "Mappa di rete",                                   "es": "Mapa de red",                                     "pl": "Mapa sieci"},
    "Pairing process": {                             "en": "Pairing process",                                 "de": "Paarungsprozess",                                 "ru": "Процесс спаривания",                              "pt": "Processo de emparelhamento",                      "nl": "Koppelingsproces",                                "fr": "Processus d'appariement",                         "it": "Processo di accoppiamento",                       "es": "Proceso de emparejamiento",                       "pl": "Proces parowania"},
    "Rename device": {                               "en": "Rename device",                                   "de": "Benennen Sie das Gerät um",                       "ru": "Переименовать устройство",                        "pt": "Renomear dispositivo",                            "nl": "Apparaat hernoemen",                              "fr": "Renommer l'appareil",                             "it": "Rinomina dispositivo",                            "es": "Renombrar dispositivo",                           "pl": "Zmień nazwę urządzenia"},
    "Save": {                                        "en": "Save",                                            "de": "Speichern",                                       "ru": "Сохранить",                                       "pt": "Salve ",                                         "nl": "Opslaan",                                         "fr": "sauvegarder",                                     "it": "Salvare",                                         "es": "Salvar",                                          "pl": "Zapisać"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Настройки",                                       "pt": "Definições",                                      "nl": "instellingen",                                    "fr": "Paramètres",                                      "it": "impostazioni",                                    "es": "Ajustes",                                         "pl": "Ustawienia"},
    "Yes": {                                         "en": "Yes",                                             "de": "Ja",                                              "ru": "Да",                                              "pt": "sim",                                             "nl": "Ja",                                              "fr": "Oui",                                             "it": "sì",                                              "es": "Sí",                                              "pl": "tak"},
    "Zigbee adapter": {                              "en": "Zigbee adapter",                                  "de": "Zigbee-Adapter",                                  "ru": "Zigbee драйвер",                                  "pt": "Adaptador Zigbee",                                "nl": "Zigbee-adapter",                                  "fr": "Adaptateur Zigbee",                               "it": "Adattatore Zigbee",                               "es": "Adaptador zigbee",                                "pl": "Adapter Zigbee"},
    "Disable Queue": {                      "en": "Disable Queue",                          "de": "Queue deaktivieren",                     "ru": "Выключить Queue",                  "pt": "Desativar Queue",                       "nl": "Schakel Queue",                     "fr": "Désactiver le Queue",                "it": "Disabilita Queue",                       "es": "Desactivar Queue",                      "pl": "Wyłącz Queue"},

};
